No need to cleanup if .git is missing.
Signed-off-by: Marko Saukko <marko.saukko@jollamobile.com>

diff --git a/gp_common b/gp_common
--- a/gp_common
+++ b/gp_common
@@ -71,6 +71,9 @@ git_tag_cleanly() {
 }
 
 cleanup(){
+    # If there is no .git directory there is nothing to cleanup.
+    [[ -d .git ]] || return
+
     echo "Attempting to switch back to $initial_branch in git"
     git checkout -f $initial_branch
     if [[ $tag_cleanup_list ]] ; then
