Use fatal() and validate pkg-dir
Signed-off-by: David Greaves <david@dgreaves.com>

diff --git a/gp_release b/gp_release
--- a/gp_release
+++ b/gp_release
@@ -20,7 +20,7 @@ git_tag_exists() { git show-ref --tags --quiet --verify -- "refs/tags/$1"; }
 git_branch_exists() { git show-ref --quiet --verify -- "refs/heads/$1"; }
 
 switch_to_pkg(){
-    git checkout -f pkg-$DISTRO || { echo "Can't checkout pkg-$DISTRO, aborting"; exit 1; }
+    git checkout -f pkg-$DISTRO || { fatal "Can't checkout pkg-$DISTRO, aborting"; }
 }
 
 cleanup(){
@@ -118,8 +118,7 @@ do_release() {
 	    --base=*)
 		newbase=${1#*=}
 		if not git_tag_exists $newbase; then
-		    echo "--base must provide a valid tag. '$newbase' is not a valid tag."
-		    exit 1
+		    fatal "--base must provide a valid tag. '$newbase' is not a valid tag."
 		fi
 		# if a plain --ver is given aswell (ie without
 		# =ver-rel) that's ambiguous since --base implies a
@@ -137,8 +136,7 @@ do_release() {
 		    ver=${verrel%-*}
 		    rel=${verrel##*-}
 		else
-		    echo "The --ver= option must provide <ver>-<rel>"
-		    exit 1
+		    fatal "The --ver= option must provide <ver>-<rel>"
 		fi
 		# if $verrel is "" then we guess it later when the packaging is present
 		shift ;;
@@ -152,9 +150,8 @@ do_release() {
 		    if git --git-dir $gitdir/.git rev-parse --git-dir > /dev/null 2>&1; then
 			gitdir=$gitdir/.git
 		    else
-			echo "The --git-dir option must point to a git repo."
-			echo "  $gitdir nor $gitdir/.git are a git directory"
-			exit 1
+			fatal "The --git-dir option must point to a git repo. \n" \
+                            "$gitdir nor $gitdir/.git are a git directory"
 		    fi
 		fi
 		export GIT_WORK_TREE=$(pwd)
@@ -169,10 +166,8 @@ do_release() {
 	esac
     done
 
-    git rev-parse --git-dir > /dev/null 2>&1 || {
-	echo "This is not a git repository; use $ME in a gitpkg git repo or use --git-dir".
-	exit 1
-    }
+    git rev-parse --git-dir > /dev/null 2>&1 || 
+	fatal "This is not a git repository; use $ME in a gitpkg git repo or use --git-dir."
 
     # We need a clean tree unless we're in another directory using --git-dir
     if ! [[ $GIT_INDEX_FILE ]]; then require_clean_work_tree "run $ME"; fi
@@ -195,9 +190,9 @@ do_release() {
 	    echo "Automagically guessed $ver-$oldrel -> $ver-$rel"
 	    verrel=$ver-$rel
 	    if ! [[ $rel ]] || [[ $rel == "1" ]]; then
-		echo "The value guessed for Release: is '$rel' and this is probably wrong. Please specify an exact value for --ver="
-		echo "Currently Version: $ver and Release: $oldrel"
-		exit 1
+		fatal "The value guessed for Release: is '$rel' and this is probably wrong.\n" \
+                    "Please specify an exact value for --ver=\n" \
+		    "Currently Version: $ver and Release: $oldrel"
 	    fi
 	    ;;
 	newbase )
@@ -241,8 +236,7 @@ do_release() {
 	pkgfile=$(find . -maxdepth 1 -name '*spec' -print -quit)
     fi
     if [[ ! $pkgfile ]]; then
-	print "No spec or yaml files found"
-	exit 1
+	fatal "No spec or yaml files found"
     fi
 
     if [[ $verrel ]]; then
diff --git a/gp_setup b/gp_setup
--- a/gp_setup
+++ b/gp_setup
@@ -8,8 +8,7 @@
 . ${GP_LIB:=/usr/share/gitpkg}/gp_common
 
 [[ -d .git ]] || {
-    echo "This is not a git repository; use gp_setup when you've cloned or created a normal src repo that is ready for packaging".
-    exit 1
+    fatal "This is not a git repository; use gp_setup when you've cloned or created a normal src repo that is ready for packaging".
 }
 
 trap cleanup EXIT
@@ -22,7 +21,7 @@ usage() {
              --pkgdir=<packaging dir> \
              [--patch-branch=<branch/tag>]  [--pristine] \
              [--distro=<DISTRO>]
- 
+
        Used to setup an existing git repo for git-pkg
 
        $DISTRO is set either in ~/.gitpkg, the GITPKG_DISTRO
@@ -90,7 +89,7 @@ cat <<EOF
                   <packaging dir> for a tarball and uses that as the
                   basis for the build.  Unpacks the tarball as an
                   initial commit and applies the given tag to the
-                  unpacked tarball
+                  unpacked tarball.
 
        --ver=<ver>[-<rel>]
                   If the upstream <basetag> is not the X.Y.Z version
@@ -137,6 +136,8 @@ use_existing() {
 		# Would be nice to default to tag=version
 		unpack=true
 		basetag=${1#*=}
+		# Make a git repo if there isn't one
+		if ! [[ -d .git ]]; then git init; fi
 		shift ;;
 	    --pkgdir=* )
 		pkgdir=${1#*=}
@@ -155,13 +156,14 @@ use_existing() {
 		USE_ALL_PKG=true
 		shift ;;
 	    * )
-		echo "Error $1 not recognised"
-		exit 1;;
+		fatal "Error $1 not recognised";;
 	esac
     done
 
-    [[ $basetag ]] || { echo "tag not supplied"; exit 1; }
-    [[ $pkgdir ]] || { echo "pkgdir not supplied"; exit 1; }
+    [[ $basetag ]] || { fatal "tag not supplied"; }
+    [[ $pkgdir ]] || { fatal "You must supply --pkgdir when using --auto"; }
+    [[ -d $pkgdir ]] || { fatal "Supplied --pkgdir '$pkgdir' is not a directory"; }
+
 
     # Determine version/release numbers
     get_verrel_from_packaging $pkgdir
@@ -184,16 +186,14 @@ use_existing() {
     pbranch="${DISTRO}-master"
 
     if ! [[ -d .git ]]; then
-	echo "This is not a git repository"
-	exit 1
+	fatal "This is not a git repository"
     fi
 
     # Verify there's only a single spec or yaml file.
     numspec=$(ls $pkgdir/*spec 2>/dev/null | wc -l)
     numyaml=$(ls $pkgdir/*yaml 2>/dev/null | wc -l)
     if [[ $numspec -gt 1 ]] || [[ $numyaml -gt 1 ]]; then
-	echo "gp_setup doesn't support packaging with >1 .spec or .yaml file"
-	exit 1
+	fatal "gp_setup doesn't support packaging with >1 .spec or .yaml file"
     fi
 
     # ... and record it
@@ -209,7 +209,7 @@ use_existing() {
     # the tarball as a starting point
     if [[ $gp_type == "pristine-tar" && $unpack ]] ; then
 	echo "Pristine tar : Unpacking tarball as initial commit"
-	unpack_tarball $pkgdir/$tarball	
+	unpack_tarball $pkgdir/$tarball
 	git add .
 	git commit -q -m"Initial commit from $tarball"
 	# Create a tag for the tarball - it's OK to do it now in unpack mode
@@ -235,7 +235,7 @@ use_existing() {
 	echo "Pristine tar : removing all files and unpacking tarball to record any delta to $basetag"
 	pristine-tar commit $pkgdir/$tarball $basetag
 	branch_cleanup_list+=" pristine-tar"
-	unpack_tarball $pkgdir/$tarball	
+	unpack_tarball $pkgdir/$tarball
 	git add .; git ls-files --deleted | xargs --no-run-if-empty git rm
 	git commit -q --allow-empty -m"pristine-tar-delta: Import any changes from the released tarball into the $DISTRO source tree ready for local patches"
 	have_patches=1
@@ -245,7 +245,7 @@ use_existing() {
     # We'll probably need a --fuzz option at some point
     # Keep the dir clean and we should abort/warn when patches don't apply
     for patch in $(cd $pkgdir; grep Patch.*: *spec | cut -f2 -d:); do
-	
+
 	echo Applying $patch
 	if ! patch $FUZZ -p1 --no-backup-if-mismatch -s < $pkgdir/$patch; then
 	    echo "Patch $pkgdir/$patch seemed to apply badly - fixup in a different terminal and press return to commit it and continue"
@@ -290,14 +290,14 @@ use_existing() {
 	if [[ $gp_type != "pristine-tar" ]] ; then
 	    echo "SetupOptions: -q -n src"  >> $yamlfile
 	fi
-	gp_mkpkg --no-checkout --no-tarball || exit 1
+	gp_mkpkg --no-checkout --no-tarball || fatal "gp_mkpkg failed"
 
 	specify -N $yamlfile
     else
 	if [[ $gp_type == "pristine-tar" ]] ; then
-	    gp_mkpkg -n --no-tarball  --no-src  || exit 1
+	    gp_mkpkg -n --no-tarball  --no-src  || fatal "gp_mkpkg failed"
 	else
-	    gp_mkpkg -n --no-tarball  || exit 1
+	    gp_mkpkg -n --no-tarball  || fatal "gp_mkpkg failed"
 	fi
     fi
 
@@ -309,7 +309,7 @@ use_existing() {
     git_tag_cleanly $pkg_tag
 
     # Comment on what we've created
-    echo Used: 
+    echo Used:
     cat _src
     echo for _src
 
@@ -354,6 +354,7 @@ do_pkg() {
 	case $1 in
 	    --pkgdir=* )
 		pkgdir=${1#*=}
+		[[ -d $pkgdir ]] || { fatal "Supplied --pkgdir '$pkgdir' is not a directory"; }
 		shift ;;
 	    --ver=* )
 		verrel=${1#*=}
@@ -361,13 +362,11 @@ do_pkg() {
 		    ver=${verrel%-*}
 		    rel=${verrel##*-}
 		else
-		    echo "The --ver= option must provide <ver>-<rel>"
-		    exit 1
+		    fatal "The --ver= option must provide <ver>-<rel>"
 		fi
 		shift ;;
 	    * )
-		echo "Error $1 not recognised"
-		exit 1;;
+		fatal "Error $1 not recognised" ;;
 	esac
     done
 
@@ -377,7 +376,7 @@ do_pkg() {
 
     # If all goes well we'll tag current location
     ver_tag_sha1=$(git rev-parse HEAD)
-    
+
     prepare_pkg_branch
 
     if [[ $pkgdir ]]; then
@@ -432,8 +431,7 @@ fi
 prepare_pkg_branch() {
     # Verify there's no packaging branch already
     if git show-ref --verify --quiet refs/heads/${pkg_branch}; then
-	echo "${pkg_branch} branch exists already"
-	exit 1
+	fatal "${pkg_branch} branch exists already"
     fi
 
     require_clean_work_tree "run $ME"
